language: objective-c


before_install:
   - brew install mulle-kybernetik/alpha/mulle-build

script:
   - mulle-bootstrap init
   - mulle-bootstrap setting -g -r repositories https://github.com/mulle-nat/Foobie.git
   - echo "project( empty)" > CMakeLists.txt
   - mulle-build -vvv -V
